name: Sobelow SAST

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '30 16 * * 6'

permissions:
  contents: read

jobs:
  security-scan:
    permissions:
      contents: read
      security-events: write
      actions: read
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - id: run-action
        uses: sobelow/action@v1
        with:
          flags: --format json
      - name: Upload report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
